/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.ItemEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Inesc28
 */
public class generarPagoss extends javax.swing.JPanel {
  ButtonGroup moneda;
  ButtonGroup metodos_pago;
    /**
     * Creates new form generarPagoss
     */
    public generarPagoss() {
        initComponents();
        radioButtonsEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_metodo_pago = new javax.swing.JPanel();
        jRadio_pago_movil = new javax.swing.JRadioButton();
        jRadio_efectivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel_moneda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadio_bolivares = new javax.swing.JRadioButton();
        jRadio_dolares = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_metodo_pago.setBackground(new java.awt.Color(102, 255, 255));

        jRadio_pago_movil.setBackground(new java.awt.Color(102, 255, 255));
        jRadio_pago_movil.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jRadio_pago_movil.setText("Pago Móvil");
        jRadio_pago_movil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRadio_efectivo.setBackground(new java.awt.Color(102, 255, 255));
        jRadio_efectivo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jRadio_efectivo.setText("Efectivo");
        jRadio_efectivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Método de Pago");

        javax.swing.GroupLayout jPanel_metodo_pagoLayout = new javax.swing.GroupLayout(jPanel_metodo_pago);
        jPanel_metodo_pago.setLayout(jPanel_metodo_pagoLayout);
        jPanel_metodo_pagoLayout.setHorizontalGroup(
            jPanel_metodo_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_metodo_pagoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel_metodo_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel_metodo_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadio_pago_movil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadio_efectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel_metodo_pagoLayout.setVerticalGroup(
            jPanel_metodo_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_metodo_pagoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jRadio_pago_movil)
                .addGap(26, 26, 26)
                .addComponent(jRadio_efectivo)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jPanel_moneda.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Moneda");

        jRadio_bolivares.setBackground(new java.awt.Color(0, 204, 204));
        jRadio_bolivares.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jRadio_bolivares.setText("Bolívares");

        jRadio_dolares.setBackground(new java.awt.Color(0, 204, 204));
        jRadio_dolares.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jRadio_dolares.setText("Dólares");

        javax.swing.GroupLayout jPanel_monedaLayout = new javax.swing.GroupLayout(jPanel_moneda);
        jPanel_moneda.setLayout(jPanel_monedaLayout);
        jPanel_monedaLayout.setHorizontalGroup(
            jPanel_monedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_monedaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel_monedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio_dolares)
                    .addGroup(jPanel_monedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRadio_bolivares, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_monedaLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(13, 13, 13))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel_monedaLayout.setVerticalGroup(
            jPanel_monedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_monedaLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addComponent(jRadio_bolivares)
                .addGap(28, 28, 28)
                .addComponent(jRadio_dolares)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inescoro/icons/caja.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Paciente (ID) :");

        jTextField1.setBackground(new java.awt.Color(153, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Monto :");

        jTextField2.setBackground(new java.awt.Color(153, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Ref :");

        jTextField3.setBackground(new java.awt.Color(153, 255, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PROCESAR PAGO");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel_metodo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_metodo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

     public void showWarning() {
      JOptionPane.showMessageDialog(this, "Debe completar todos los campos", "Warning", JOptionPane.WARNING_MESSAGE);  
  }
  public void showWarning2() {
      JOptionPane.showMessageDialog(this, "Debe de seleccionar una moneda", "Warning", JOptionPane.WARNING_MESSAGE);  
  }
  public void showWarning3() {
      JOptionPane.showMessageDialog(this, "Debe de seleccionar un metodo de pago ", "Warning", JOptionPane.WARNING_MESSAGE);  
  }
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if (jTextField1.getText().isEmpty() || 
              jTextField2.getText().isEmpty() ||
              jTextField3.getText().isEmpty()) {

                showWarning(); 

        } else if (moneda.getSelection() == null) {
              showWarning2();  
        } else if (metodos_pago.getSelection()== null){

           showWarning3();

        }else{
            
            // Process payment... 
        }
           
    
    }//GEN-LAST:event_jButton1ActionPerformed

    // manejar RadioButtons
    public void radioButtonsEvent() {
         metodos_pago = new ButtonGroup();
         moneda = new ButtonGroup();
        
        // Obtener los hijos de los paneles Metodo de pago y Moneda
        Component[] metodo_radio_buttons = jPanel_metodo_pago.getComponents();
        Component[] moneda_radio_buttons = jPanel_moneda.getComponents();
        
        // Agregar al grupo de botones correspondiente
        for (Component radio : metodo_radio_buttons) {
            // Check if the component is a JRadioButton
            if (radio instanceof JRadioButton) {
              metodos_pago.add((JRadioButton) radio);
            }
        }
        // Agregar al grupo de botones correspondiente
        for (Component radio : moneda_radio_buttons) {
            // Check if the component is a JRadioButton
            if (radio instanceof JRadioButton) {
              moneda.add((JRadioButton) radio);
            }
        }
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_metodo_pago;
    private javax.swing.JPanel jPanel_moneda;
    private javax.swing.JRadioButton jRadio_bolivares;
    private javax.swing.JRadioButton jRadio_dolares;
    private javax.swing.JRadioButton jRadio_efectivo;
    private javax.swing.JRadioButton jRadio_pago_movil;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
