/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.awt.Dimension;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

/**
 *
 * @author Inesc28
 */
public class panelIngresos extends javax.swing.JPanel {

    /**
     * Creates new form panelIngresos
     */
    public panelIngresos() {
        initComponents();
        graficar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void graficar() {
        int monto_d = 0;
        int monto_s = 0;
        int monto_m = 0;

        // Accedemos al archivo de ingresos
        String filePath = System.getProperty("user.dir") + File.separator + "src"
        + File.separator + "temp" + File.separator + "ingresos.txt";
        File file = new File(filePath);

        if (!file.exists()) {
            // Crea el archivo si no existe
            try {
                file.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        try {
            List<String> lines = Files.readAllLines(Paths.get(filePath));

            for (String line : lines) {
                String[] split = line.split("\\|");

                if (split[0].isEmpty()) {
                    continue;  // Salta esta línea vacía
                }

                int cantidad = Integer.parseInt(split[0]);
                int dia = Integer.parseInt(split[1]);
                int mes = Integer.parseInt(split[2]);
                int anio = Integer.parseInt(split[3]);
                // Encontramos su ubicacion en el tiempo
                String ref = dia + " " + mes + " " + anio;

                switch (classifyDate(dia, mes, anio)) {
                    case "Today": {
                        //System.out.println("Today: " + ref + " Monto: " + cantidad);
                        monto_d += cantidad;
                        break;
                    }
                    case "Week": {
                        //System.out.println("Week: " + ref + " Monto: " + cantidad);
                        monto_s += cantidad;
                        break;
                    }
                    case "Month": {
                        //System.out.println("Moth: " + ref + " Monto: " + cantidad);
                        monto_m += cantidad;
                        break;
                    }
                    // Older
                    default: {
                        // System.out.println("Older: " + ref + " Monto: " + cantidad);
                        break;
                    }
                }
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        // Cargamos información
        DefaultPieDataset datos = new DefaultPieDataset();
        datos.setValue("Promedio Mensual", monto_m);
        datos.setValue("Promedio Semanal", monto_s);
        datos.setValue("Promedio al Día", monto_d);

        JFreeChart torta = ChartFactory.createPieChart("Promedio de Ingresos", datos, true, true, false);

        ChartPanel panel = new ChartPanel(torta);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(785, 313));

        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(panel, BorderLayout.NORTH);
        this.revalidate();
        this.repaint();
    }
    
    public String classifyDate(int day, int month, int year) {

        LocalDate today = LocalDate.now();

        // La fecha dada 
        LocalDate givenDate = LocalDate.of(year, month, day);

        // Calcular la diferencia en días 
        long daysBetween = ChronoUnit.DAYS.between(givenDate, today);

        if (daysBetween == 0) {
            return "Today";
        } else if (daysBetween > 0 && daysBetween <= 7) {
            return "Week";
        } else if (daysBetween > 7 && daysBetween <= 30) {
            return "Month";
        } else {
            return "Older";
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
