/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Inesc28
 */
public class resumAct extends javax.swing.JPanel {

    /**
     * Creates new form resumAct
     */
    public resumAct() {
        initComponents();
        graficar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void graficar() {
        int material_recibido = 0;
        int pacientes_atendidos = 0;
        int gastos_realizados = 0;
        int cantidad_pagos = 0;

        int[] valores = {material_recibido, pacientes_atendidos, gastos_realizados, cantidad_pagos};

        String filePath = System.getProperty("user.dir") + File.separator + "src"
                + File.separator + "temp" + File.separator;
        String[] files = {filePath + "material_recibido.txt", filePath + "pacientes_atendidos.txt",
            filePath + "gastos_realizados.txt", filePath + "cantidad_pagos.txt"};

        for (int i = 0; i < files.length; i++) {

            File file = new File(files[i]);

            if (!file.exists()) {
                // Crea el archivo si no existe
                try {
                    file.createNewFile();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            // Leer archivo y sumar valores 
            try {
                List<String> lines = Files.readAllLines(Paths.get(files[i]));

                for (String line : lines) {
                    int valor = Integer.parseInt(line);
                    valores[i] += valor;
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        // Asignar valores del array a las variables  
        material_recibido = valores[0];
        pacientes_atendidos = valores[1];
        gastos_realizados = valores[2];
        cantidad_pagos = valores[3];

        DefaultPieDataset datos = new DefaultPieDataset();
        datos.setValue("Pacientes Atendidos", pacientes_atendidos);
        datos.setValue("Cantidad de Pagos", cantidad_pagos);
        datos.setValue("Gastos Realizados", gastos_realizados);
        datos.setValue("Material Recibido", material_recibido);

        JFreeChart torta = ChartFactory.createPieChart("Resumen de Actividad", datos, true, true, false);

        ChartPanel panel = new ChartPanel(torta);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(667, 375));

        jPanel7.setLayout(new BorderLayout());
        jPanel7.add(panel, BorderLayout.NORTH);

        this.revalidate();
        this.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
